[[redirects]]
from = "/api/"
to = "https://google-doc-backend.vercel.app/"
status = 200
force = true
headers = {X-From = "Netlify”}
[[headers]]
for = "/”
[headers.values]
Access-Control-Allow-Origin = "*”